github: []
patreon: ledino
open_collective: ""
ko_fi: ledino
buy_me_a_coffee: ledino
liberapay: ""
tidelift: ""
community_bridge: ""
custom:
  - "https://ko-fi.com/ledino"
  - "https://www.buymeacoffee.com/ledino"
