#
# Module manifest for module 'SecureGen'
#
# Generated by: Ledino & Copilot
# Updated on: 18/02/2026
#

@{


# Script module associated with this manifest
RootModule = 'SecureGen.psm1'

# Version number of this module
ModuleVersion = '1.5.0'

# Supported PowerShell editions
CompatiblePSEditions = @('Desktop', 'Core')

# Unique module ID
GUID = 'b4f7c2c3-1c9e-4e4d-9f8a-9e2a4c1d7a31'

# Author information
Author = 'Ledino'
CompanyName = 'SecureGen Project'
Copyright = '(c) 2026'

# Module description
Description = 'Module PowerShell moderne pour générer des mots de passe, passphrases et des clés sécurisées. Compatible PowerShell 5 et 7, avec clipboard cross-platform et ergonomie soignée.'

# Minimum PowerShell version
PowerShellVersion = '5.1'

# Nested modules (none)
NestedModules = @()

# Public functions exported by this module
FunctionsToExport = @(
    'Get-PassWord',
    'Get-PassPhrase',
    'Get-CryptoIndex',
    'Invoke-Beep',
    'Set-ClipboardSafe',
    'Clear-ClipboardSafe',
    'Get-PKIPass',
    'Convert-ToSecureStringSafe'
)

# Cmdlets to export
CmdletsToExport = @()

# Variables to export
VariablesToExport = '*'

# Aliases to export
AliasesToExport = @('sgp', 'sgw', 'sgpki')

# Private data
PrivateData = @{

    PSData = @{

        # Tags for PSGallery
        Tags = @(
            'Security','Password','Passphrase','Clipboard',
            'PowerShell','CrossPlatform','Crypto','PKI','SecureString'
        )

        # License URL
        LicenseUri = 'https://opensource.org/licenses/MIT'

        # Project URL
        ProjectUri = 'https://github.com/ledino/SecureGen'

        # Icon URL
        IconUri = 'https://raw.githubusercontent.com/ledino/SecureGen/main/assets/logo.png'

        # Release notes
        ReleaseNotes = @'
Version 1.5.0 :
- Nouveau : Get-PKIPass (Password / Passphrase + SecureString)
- Nouveau : Convert-ToSecureStringSafe
- Nouveau : Set-ClipboardSafe & Clear-ClipboardSafe
- Get-PassWord : ajout de -RequireAllTypes
- Harmonisation API (Words / Len)
- Documentation entièrement mise à jour (PlatyPS)
- Tests Pester complets (PKIPass + ClipboardSafe)
- Corrections de paramètres & messages d''erreur
'@
    }
}

}