name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-pwsh@v1

      - name: Test module loads
        shell: pwsh
        run: Import-Module ./SecureGen/SecureGen.psd1